/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary:          "#000921",
        "primary-container": "#0f2041",
        "primary-fixed":  "#d9e2ff",
        "primary-fixed-dim": "#b6c6f0",
        "on-primary":     "#ffffff",
        "on-primary-container": "#7988af",
        "on-primary-fixed": "#081a3b",
        "on-primary-fixed-variant": "#374669",
        "inverse-primary": "#b6c6f0",

        secondary:        "#7a590f",
        "secondary-container": "#fed17d",
        "secondary-fixed": "#ffdea6",
        "secondary-fixed-dim": "#ecc06e",
        "on-secondary":   "#ffffff",
        "on-secondary-container": "#78580e",
        "on-secondary-fixed": "#271900",
        "on-secondary-fixed-variant": "#5e4200",

        tertiary:         "#150700",
        "tertiary-container": "#361a00",
        "tertiary-fixed": "#ffdcc1",
        "tertiary-fixed-dim": "#f0bc92",
        "on-tertiary":    "#ffffff",
        "on-tertiary-container": "#ac7f59",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#623f1e",

        surface:          "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim":    "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-tint":   "#4f5e82",
        "on-surface":     "#0b1c30",
        "on-surface-variant": "#45464e",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",

        background:       "#f8f9ff",
        "on-background":  "#0b1c30",

        outline:          "#75777f",
        "outline-variant": "#c5c6cf",

        error:            "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error":       "#ffffff",
        "on-error-container": "#93000a",

        "canvas-white":   "#FFFFFF",
        "deep-navy-dark": "#081226",
        "gold-light":     "#DCC08A",
        "silver-metallic": "#E2E8F0",
      },
      fontFamily: {
        "display-lg":        ["EB Garamond", "Georgia", "serif"],
        "display-lg-mobile": ["EB Garamond", "Georgia", "serif"],
        "headline-xl":       ["EB Garamond", "Georgia", "serif"],
        "headline-md":       ["EB Garamond", "Georgia", "serif"],
        "body-lg":           ["Manrope", "system-ui", "sans-serif"],
        "body-md":           ["Manrope", "system-ui", "sans-serif"],
        "button-text":       ["Manrope", "system-ui", "sans-serif"],
        "label-caps":        ["Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg":        ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "500" }],
        "headline-xl":       ["48px", { lineHeight: "56px", fontWeight: "400" }],
        "headline-md":       ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg":           ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":           ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "button-text":       ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-caps":        ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile":  "16px",
        "margin-desktop": "64px",
        "section-gap":    "120px",
        gutter:           "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
